# Generated by Django 6.0.8 on 2026-08-14 19:06

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('EVENT', 'Event'), ('VOLUNTEERING', 'Volunteering'), ('CONSULTATION', 'Consultation'), ('PETITION', 'Petition'), ('SURVEY', 'Survey'), ('ORGANIZATION', 'Organization'), ('OTHER', 'Other')], max_length=24)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(max_length=16)),
                ('organizer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('participation_mode', models.CharField(choices=[('IN_PERSON', 'In person'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid'), ('UNSPECIFIED', 'Unspecified')], max_length=16)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('action_kind', models.CharField(choices=[('REGISTER', 'Register'), ('APPLY', 'Apply'), ('SIGN', 'Sign'), ('RESPOND', 'Respond'), ('JOIN', 'Join'), ('LEARN_MORE', 'Learn more')], max_length=20)),
                ('action_url', models.URLField(max_length=1000)),
                ('source_url', models.URLField(max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('WITHDRAWN', 'Withdrawn')], default='PUBLISHED', max_length=16)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField()),
                ('consecutive_missing_syncs', models.PositiveSmallIntegerField(default=0)),
                ('geocoding_provider', models.CharField(blank=True, max_length=64)),
                ('geocoding_input_hash', models.CharField(blank=True, max_length=64)),
                ('geocoding_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('NO_MATCH', 'No match'), ('RETRYABLE_FAILURE', 'Retryable failure')], default='PENDING', max_length=24)),
                ('geocoding_metadata', models.JSONField(blank=True, default=dict)),
                ('geocoding_last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='ingestion.source')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'starts_at', 'ends_at'], name='opportuniti_status_721557_idx'), models.Index(fields=['country_code'], name='opportuniti_country_be9b8b_idx'), models.Index(fields=['language'], name='opportuniti_languag_06789b_idx'), models.Index(fields=['participation_mode'], name='opportuniti_partici_d1d3c0_idx'), django.contrib.postgres.indexes.GistIndex(fields=['location'], name='opportunity_location_gist')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_external_id'), models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at'))), name='opportunity_end_not_before_start')],
            },
        ),
    ]
