# Generated by Django 6.0.8 on 2026-08-16 13:02

import hashlib
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models

TRACKING_QUERY_PARAMETERS = {
    "fbclid",
    "gclid",
    "mc_cid",
    "mc_eid",
}


def canonical_url_hash(value):
    if not value:
        return ""
    parsed = urlsplit(value.strip())
    query = urlencode(
        sorted(
            (key, item)
            for key, item in parse_qsl(parsed.query, keep_blank_values=True)
            if not key.lower().startswith("utm_") and key.lower() not in TRACKING_QUERY_PARAMETERS
        )
    )
    normalized = urlunsplit(
        (
            parsed.scheme.lower(),
            parsed.netloc.lower(),
            parsed.path.rstrip("/") or "/",
            query,
            parsed.fragment,
        )
    )
    return hashlib.sha256(normalized.encode()).hexdigest()


def backfill_deduplication_inputs(apps, schema_editor):
    Opportunity = apps.get_model("opportunities", "Opportunity")
    pending = []
    for opportunity in Opportunity.objects.select_related("source").iterator(chunk_size=500):
        adapter_key = opportunity.source.adapter_key
        if adapter_key == "eu_youth_events.v1":
            opportunity.source_entity_id = opportunity.external_id.partition(":")[0]
        elif adapter_key == "eurodesk_learning.v1":
            opportunity.source_entity_id = opportunity.external_id.rpartition("-")[0]

        if opportunity.starts_at is not None:
            opportunity.starts_at_precision = "DATETIME"
        if opportunity.application_deadline_at is not None:
            opportunity.application_deadline_at_precision = (
                "DATE" if adapter_key == "eurodesk_learning.v1" else "DATETIME"
            )
        opportunity.source_url_hash = canonical_url_hash(opportunity.source_url)
        opportunity.action_url_hash = canonical_url_hash(opportunity.action_url)
        pending.append(opportunity)
        if len(pending) == 500:
            Opportunity.objects.bulk_update(
                pending,
                (
                    "source_entity_id",
                    "starts_at_precision",
                    "application_deadline_at_precision",
                    "source_url_hash",
                    "action_url_hash",
                ),
            )
            pending.clear()
    if pending:
        Opportunity.objects.bulk_update(
            pending,
            (
                "source_entity_id",
                "starts_at_precision",
                "application_deadline_at_precision",
                "source_url_hash",
                "action_url_hash",
            ),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0006_importrun_duplicates_linked_and_more"),
        ("opportunities", "0005_flat_opportunity_kinds"),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name="DuplicateDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("algorithm_version", models.CharField(max_length=100)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("DISTINCT", "Distinct"),
                            ("MATCHED", "Matched"),
                            ("UNCERTAIN", "Uncertain"),
                        ],
                        max_length=16,
                    ),
                ),
                ("score", models.FloatField(blank=True, null=True)),
                ("evidence_coverage", models.FloatField(default=0)),
                ("features", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="action_url_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="application_deadline_at_precision",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("DATE", "Date only"),
                    ("DATETIME", "Date and time"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="deduplication_embedding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="ingestion.embeddingresult",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="duplicate_algorithm_version",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="duplicate_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="duplicate_input_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicate_records",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="duplicate_status",
            field=models.CharField(
                choices=[
                    ("NOT_CHECKED", "Not checked"),
                    ("UNIQUE", "No duplicate found"),
                    ("DUPLICATE", "Linked duplicate"),
                    ("UNCERTAIN", "Published uncertain match"),
                ],
                default="NOT_CHECKED",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="source_entity_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="source_url_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="starts_at_precision",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("DATE", "Date only"),
                    ("DATETIME", "Date and time"),
                ],
                default="UNKNOWN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="temporal_timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.RunPython(backfill_deduplication_inputs, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="opportunity",
            index=django.contrib.postgres.indexes.GistIndex(
                django.contrib.postgres.indexes.OpClass("title", name="gist_trgm_ops"),
                name="opportunity_title_trgm",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(fields=["status", "duplicate_of"], name="opportunity_public_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["source", "source_entity_id"], name="opportunity_source_entity_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(("pk", models.F("duplicate_of")), _negated=True),
                name="opportunity_not_duplicate_of_self",
            ),
        ),
        migrations.AddField(
            model_name="duplicatedecision",
            name="matched_opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_duplicate_decisions",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="duplicatedecision",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicate_decisions",
                to="opportunities.opportunity",
            ),
        ),
        migrations.AddIndex(
            model_name="duplicatedecision",
            index=models.Index(
                fields=["outcome", "created_at"], name="duplicate_decision_outcome_idx"
            ),
        ),
    ]
