# Generated by Django 6.0.8 on 2026-08-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adapter_key', models.CharField(max_length=100, unique=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('sync_interval', models.DurationField()),
                ('enabled', models.BooleanField(default=True)),
                ('attribution_name', models.CharField(max_length=255)),
                ('attribution_text', models.TextField()),
                ('attribution_url', models.URLField(max_length=1000)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='RUNNING', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('opportunities_created', models.PositiveIntegerField(default=0)),
                ('opportunities_updated', models.PositiveIntegerField(default=0)),
                ('records_unchanged', models.PositiveIntegerField(default=0)),
                ('records_ignored', models.PositiveIntegerField(default=0)),
                ('records_rejected', models.PositiveIntegerField(default=0)),
                ('records_missing', models.PositiveIntegerField(default=0)),
                ('geocoding_succeeded', models.PositiveIntegerField(default=0)),
                ('geocoding_no_match', models.PositiveIntegerField(default=0)),
                ('geocoding_failed', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_runs', to='ingestion.source')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
