# Generated by Django 6.0.8 on 2026-08-16 13:02

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0005_importrun_classification_counters"),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name="importrun",
            name="duplicates_linked",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importrun",
            name="duplicates_uncertain",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importrun",
            name="embeddings_cached",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importrun",
            name="embeddings_failed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importrun",
            name="embeddings_succeeded",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="EmbeddingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("embedder_key", models.CharField(max_length=100)),
                ("embedder_version", models.CharField(max_length=100)),
                ("input_hash", models.CharField(max_length=64)),
                ("provider_key", models.CharField(max_length=64)),
                ("model_key", models.CharField(max_length=100)),
                ("provider_response_id", models.CharField(blank=True, max_length=255)),
                ("dimensions", models.PositiveIntegerField()),
                ("embedding", pgvector.django.vector.VectorField()),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "embedder_key",
                            "embedder_version",
                            "provider_key",
                            "model_key",
                            "input_hash",
                        ],
                        name="embedding_cache_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "embedder_key",
                            "embedder_version",
                            "provider_key",
                            "model_key",
                            "input_hash",
                        ),
                        name="unique_embedding_version_input",
                    )
                ],
            },
        ),
    ]
