# Generated by Django 6.0.8 on 2026-08-14 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='opportunities.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'opportunity'), name='unique_user_opportunity_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('IMPRESSION', 'Impression'), ('OPEN', 'Open'), ('SAVE', 'Save'), ('UNSAVE', 'Unsave'), ('EXTERNAL_ACTION_CLICK', 'External action click')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='opportunities.opportunity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['opportunity', 'interaction_type', 'occurred_at'], name='interaction_opportu_bf3f5c_idx'), models.Index(fields=['user', 'occurred_at'], name='interaction_user_id_ecfcfd_idx')],
            },
        ),
    ]
